#!/usr/bin/env bash
# bash script to unistall nginx, don't ask

sudo systemctl stop nginx
sudo apt-get -y remove nginx
sudo apt-get -y purge nginx
sudo apt-get autoremove
sudo systemctl unmask nginx.service
sudo systemctl start nginx # should return error
