#!/usr/bin/env bash
# bash script to unistall nginx, don't ask

sudo systemctl stop nginx
sudo apt-get remove nginx
sudo apt-get purge nginx
sudo apt-get autoremove
sudo systemctl start nginx # should return error
