#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get install nginx -y
sudo apt install net-tools -y
sudo apt install nmap
sudo apt install mysql-client-core-8.0
pip3 install flask
pip3 install flask_cors
